# Generated by Django 4.2 on 2024-06-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='кто добавил'),
        ),
    ]
